/**
 * This file auto-generated by Fern from our API Definition.
 */

import { CompanyApi } from "../../..";
import * as core from "../../../core";

export type Response = core.APIResponse<void, CompanyApi.task.batchDelete.Error>;
export type Error = CompanyApi.task.batchDelete.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: CompanyApi.task.batchDelete.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}
