/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CompanyApi } from "../../..";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.TaskId.Raw[], CompanyApi.TaskId[]> = core.schemas.list(
  core.schemas.lazy(async () => (await import("../..")).TaskId)
);
