/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";

export interface CreateScheduleRequest {
  /**
   * An optional name of the Schedule. This string must not contain more
   * than 100 characters.
   *
   */
  name?: string;
  /**
   * An optional description of the Schedule. This string must not contain
   * more than 500 characters.
   *
   */
  description?: string;
  /**
   * A [cron expression](https://crontab.guru/examples.html) describing the
   * Schedule on which Schedules will run (UTC).
   *
   * Note: execution n + 1 of a Schedule will not begin until execution n has
   * completed successfully.
   *
   * You must pass either `cron` or `rrule`` when creating a new Schedule.
   *
   */
  cron?: string;
  /**
   * An [iCal RRule expression](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html)
   * describing the Schedule on which Schedules will run (UTC). The time of
   * Schedule creation will be used as the start of the recurrence interval
   * (i.e. DTSTART).
   *
   * Note: execution n + 1 of a Schedule will not begin until execution n has
   * completed successfully.
   *
   * You must pass either `cron` or `rrule`` when creating a new Schedule.
   *
   */
  rrule?: string;
  /**
   * The [ISO 8601 timestamp](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations)
   * denoting the start of an RRULE schedule.
   *
   * Example: "2021-10-01T15:53:05Z".
   *
   * When not set, it will be set to the current time, and the first Schedule will be scheduled immediately.
   * Ignored for `cron`-type Schedules.
   *
   */
  dstart?: string;
  /** If `true`, the Schedule will be paused immediately. If `false`, a paused Schedule will be resumed. */
  paused: boolean;
  request: MergentApi.HttpRequest;
}
