/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";

export interface Schedule extends MergentApi.CreateScheduleRequest {
  /** A unique ID assigned upon creation. */
  id: MergentApi.ScheduleId;
  /**
   * The [ISO 8601 timestamp](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations)
   * representing when the schedule was created.
   *
   */
  createdAt: Date;
}
