/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";

export type ScheduleId = string;

export function ScheduleId(value: string): MergentApi.ScheduleId {
  return value as unknown as MergentApi.ScheduleId;
}
