/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";

export interface CreateTaskRequest {
  /**
   * An optional name of the Task. This string must not contain more than
   * 100 characters.
   *
   */
  name?: string;
  request: MergentApi.HttpRequest;
  /**
   * The [ISO 8601 timestamp](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations)
   * for when the Task is scheduled to be executed.
   *
   * Example: "2021-10-01T15:53:05Z".
   *
   * When not present, the Task will be scheduled for immediate execution.
   *
   */
  scheduledFor?: Date;
  /**
   * The [ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations)
   * for the time to wait before the Task is executed.
   *
   * Example: "PT1M" for a delay of 1 minute.
   *
   * When both `delay` and `scheduled_for` are present, `delay` will be
   * added to `scheduled_for`.
   *
   */
  delay?: string;
}
