/**
 * This file auto-generated by Fern from our API Definition.
 */

import { CompanyApi } from "../../..";

export interface Task {
  /** A unique ID assigned upon creation. */
  id: CompanyApi.TaskId;
  /** The name of the task. */
  name?: string;
  /** The status of this Task. */
  status: CompanyApi.TaskStatus;
  request: CompanyApi.HttpRequest;
  /**
   * The ISO 8601 timestamp for when the Task is scheduled to be executed. Example: "2021-10-01T15:53:05Z".
   * When not present, the Task has been scheduled for immediate execution.
   *
   */
  scheduledFor?: Date;
  /** The ISO 8601 timestamp representing when the object was created. */
  createdAt: Date;
}
