/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";

export type TaskId = string;

export function TaskId(value: string): MergentApi.TaskId {
  return value as unknown as MergentApi.TaskId;
}
