/**
 * This file auto-generated by Fern from our API Definition.
 */

import { CompanyApi } from "../../..";

export type TaskId = string;

export function TaskId(value: string): CompanyApi.TaskId {
  return value as unknown as CompanyApi.TaskId;
}
