/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const CreateTaskRequest: core.schemas.ObjectSchema<CreateTaskRequest.Raw, MergentApi.CreateTaskRequest> =
  core.schemas.object({
    name: core.schemas.string().optional(),
    request: core.schemas.lazyObject(async () => (await import("../..")).HttpRequest),
    scheduledFor: core.schemas.property("scheduled_for", core.schemas.date().optional()),
    delay: core.schemas.string().optional(),
  });

export declare namespace CreateTaskRequest {
  interface Raw {
    name?: string | null;
    request: serializers.HttpRequest.Raw;
    scheduled_for?: string | null;
    delay?: string | null;
  }
}
