/**
 * This file auto-generated by Fern from our API Definition.
 */

import { CompanyApi } from "../../..";
import * as core from "../../../core";

export const HttpRequest: core.schemas.ObjectSchema<HttpRequest.Raw, CompanyApi.HttpRequest> = core.schemas.object({
  url: core.schemas.string(),
  headers: core.schemas.record(core.schemas.string(), core.schemas.string()).optional(),
  body: core.schemas.string().optional(),
});

export declare namespace HttpRequest {
  interface Raw {
    url: string;
    headers?: Record<string, string> | null;
    body?: string | null;
  }
}
