/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const Task: core.schemas.ObjectSchema<Task.Raw, MergentApi.Task> = core.schemas
  .object({
    id: core.schemas.lazy(async () => (await import("../..")).TaskId),
    status: core.schemas.lazy(async () => (await import("../..")).TaskStatus),
    createdAt: core.schemas.property("created_at", core.schemas.date()),
  })
  .extend(core.schemas.lazyObject(async () => (await import("../..")).CreateTaskRequest));

export declare namespace Task {
  interface Raw extends serializers.CreateTaskRequest.Raw {
    id: serializers.TaskId.Raw;
    status: serializers.TaskStatus.Raw;
    created_at: string;
  }
}
