/**
 * This file auto-generated by Fern from our API Definition.
 */

import { CompanyApi } from "../../..";
import * as core from "../../../core";

export const TaskId: core.schemas.Schema<TaskId.Raw, CompanyApi.TaskId> = core.schemas.string();

export declare namespace TaskId {
  type Raw = string;
}
