/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { MergentApi } from "../../..";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.Task.Raw[], MergentApi.Task[]> = core.schemas.list(
  core.schemas.lazyObject(async () => (await import("../..")).Task)
);
