/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as TaskClient } from "./resources/task/client/Client";

export declare namespace CompanyApiClient {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      token?: core.Supplier<core.BearerToken>;
    };
  }
}

export class CompanyApiClient {
  constructor(private readonly options: CompanyApiClient.Options) {}

  #task: TaskClient | undefined;

  public get task(): TaskClient {
    return (this.#task ??= new TaskClient(this.options));
  }
}
