/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as ScheduleClient } from "./resources/schedule/client/Client";
import { Client as TaskClient } from "./resources/task/client/Client";

export declare namespace MergentApiClient {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      token?: core.Supplier<core.BearerToken>;
    };
  }
}

export class MergentApiClient {
  constructor(private readonly options: MergentApiClient.Options) {}

  #schedule: ScheduleClient | undefined;

  public get schedule(): ScheduleClient {
    return (this.#schedule ??= new ScheduleClient(this.options));
  }

  #task: TaskClient | undefined;

  public get task(): TaskClient {
    return (this.#task ??= new TaskClient(this.options));
  }
}
