/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Production: "https://api.mergent.co/v2",
} as const;

export type Environment = typeof Environment.Production;
