/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const CreateScheduleRequest: core.schemas.ObjectSchema<
  CreateScheduleRequest.Raw,
  MergentApi.CreateScheduleRequest
> = core.schemas.object({
  name: core.schemas.string().optional(),
  description: core.schemas.string().optional(),
  cron: core.schemas.string().optional(),
  rrule: core.schemas.string().optional(),
  dstart: core.schemas.string().optional(),
  paused: core.schemas.boolean(),
  request: core.schemas.lazyObject(async () => (await import("../..")).HttpRequest),
});

export declare namespace CreateScheduleRequest {
  interface Raw {
    name?: string | null;
    description?: string | null;
    cron?: string | null;
    rrule?: string | null;
    dstart?: string | null;
    paused: boolean;
    request: serializers.HttpRequest.Raw;
  }
}
