/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";
import * as core from "../../../core";

export const ScheduleId: core.schemas.Schema<ScheduleId.Raw, MergentApi.ScheduleId> = core.schemas.string();

export declare namespace ScheduleId {
  type Raw = string;
}
