/**
 * This file auto-generated by Fern from our API Definition.
 */

import { MergentApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const Schedule: core.schemas.ObjectSchema<Schedule.Raw, MergentApi.Schedule> = core.schemas
  .object({
    id: core.schemas.lazy(async () => (await import("../..")).ScheduleId),
    createdAt: core.schemas.property("created_at", core.schemas.date()),
  })
  .extend(core.schemas.lazyObject(async () => (await import("../..")).CreateScheduleRequest));

export declare namespace Schedule {
  interface Raw extends serializers.CreateScheduleRequest.Raw {
    id: serializers.ScheduleId.Raw;
    created_at: string;
  }
}
