/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface HttpRequest {
  /**
   * The URL that the POST request will be sent to.
   *
   * For localhost development, use something like ngrok to get a publicly
   * accessible URL for your local service. See https://docs.mergent.co for
   * more info.
   *
   */
  url: string;
  /**
   * The headers that will accompany any Task's HTTP request.
   *
   * For example, you can use this to set Content-Type to
   * "application/json" or "application/octet-stream".
   *
   */
  headers?: Record<string, string>;
  /** The HTTP request body */
  body?: string;
}
